"""initial schema

Revision ID: 7fea0a113b9a
Revises: 
Create Date: 2026-02-26 18:50:59.339368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fea0a113b9a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('cemetery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'name', name='uq_cemetery_org_name')
    )
    with op.batch_alter_table('cemetery', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cemetery_org_id'), ['org_id'], unique=False)

    op.create_table('lapida_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('descripcion', sa.String(length=120), nullable=False),
    sa.Column('estado', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lapida_stock', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lapida_stock_org_id'), ['org_id'], unique=False)

    op.create_table('membership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'org_id', name='uq_membership_user_org')
    )
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=60), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('document_id', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'document_id', name='uq_person_org_document')
    )
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_person_org_id'), ['org_id'], unique=False)

    op.create_table('sepultura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('cemetery_id', sa.Integer(), nullable=False),
    sa.Column('bloque', sa.String(length=20), nullable=False),
    sa.Column('fila', sa.Integer(), nullable=False),
    sa.Column('columna', sa.Integer(), nullable=False),
    sa.Column('via', sa.String(length=20), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('modalidad', sa.String(length=60), nullable=False),
    sa.Column('estado', sa.Enum('LLIURE', 'DISPONIBLE', 'OCUPADA', 'INACTIVA', 'PROPIA', name='sepultura_estado'), nullable=False),
    sa.Column('tipo_bloque', sa.String(length=60), nullable=False),
    sa.Column('tipo_lapida', sa.String(length=60), nullable=False),
    sa.Column('orientacion', sa.String(length=30), nullable=False),
    sa.Column('sepultura_principal_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cemetery_id'], ['cemetery.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['sepultura_principal_id'], ['sepultura.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'cemetery_id', 'bloque', 'fila', 'columna', 'numero', name='uq_sepultura_location')
    )
    with op.batch_alter_table('sepultura', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sepultura_org_id'), ['org_id'], unique=False)

    op.create_table('derecho_funerario_contrato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('sepultura_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('CONCESION', 'USO_INMEDIATO', name='derecho_tipo'), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('fecha_fin >= fecha_inicio', name='ck_contract_dates'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['sepultura_id'], ['sepultura.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('derecho_funerario_contrato', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_derecho_funerario_contrato_org_id'), ['org_id'], unique=False)

    op.create_table('expediente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=40), nullable=False),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('estado', sa.String(length=40), nullable=False),
    sa.Column('sepultura_id', sa.Integer(), nullable=True),
    sa.Column('difunto_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['difunto_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['sepultura_id'], ['sepultura.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'numero', name='uq_expediente_org_number')
    )
    with op.batch_alter_table('expediente', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expediente_org_id'), ['org_id'], unique=False)

    op.create_table('inscripcion_lateral',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('sepultura_id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.String(length=255), nullable=False),
    sa.Column('estado', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['sepultura_id'], ['sepultura.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inscripcion_lateral', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inscripcion_lateral_org_id'), ['org_id'], unique=False)

    op.create_table('movimiento_sepultura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('sepultura_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('INHUMACION', 'EXHUMACION', 'TASAS', 'LAPIDA', 'CAMBIO_ESTADO', 'CONTRATO', 'INSCRIPCION_LATERAL', name='movimiento_tipo'), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('detalle', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['sepultura_id'], ['sepultura.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movimiento_sepultura', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movimiento_sepultura_fecha'), ['fecha'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimiento_sepultura_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimiento_sepultura_sepultura_id'), ['sepultura_id'], unique=False)

    op.create_table('sepultura_difunto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('sepultura_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['sepultura_id'], ['sepultura.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sepultura_difunto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sepultura_difunto_org_id'), ['org_id'], unique=False)

    op.create_table('sepultura_ubicacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('sepultura_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['sepultura_id'], ['sepultura.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'sepultura_id', 'codigo', name='uq_sepultura_ubicacion')
    )
    with op.batch_alter_table('sepultura_ubicacion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sepultura_ubicacion_org_id'), ['org_id'], unique=False)

    op.create_table('beneficiario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('activo_desde', sa.Date(), nullable=False),
    sa.Column('activo_hasta', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['contrato_id'], ['derecho_funerario_contrato.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('beneficiario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_beneficiario_org_id'), ['org_id'], unique=False)

    op.create_table('invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.Column('sepultura_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=40), nullable=False),
    sa.Column('estado', sa.Enum('BORRADOR', 'EMITIDA', 'IMPAGADA', 'PAGADA', name='invoice_estado'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contrato_id'], ['derecho_funerario_contrato.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['sepultura_id'], ['sepultura.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'numero', name='uq_invoice_org_number')
    )
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_org_id'), ['org_id'], unique=False)

    op.create_table('orden_trabajo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('expediente_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=120), nullable=False),
    sa.Column('estado', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['expediente_id'], ['expediente.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orden_trabajo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orden_trabajo_org_id'), ['org_id'], unique=False)

    op.create_table('titularidad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('activo_desde', sa.Date(), nullable=False),
    sa.Column('activo_hasta', sa.Date(), nullable=True),
    sa.Column('pensionista', sa.Boolean(), nullable=False),
    sa.Column('pensionista_desde', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['contrato_id'], ['derecho_funerario_contrato.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('titularidad', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_titularidad_org_id'), ['org_id'], unique=False)

    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('receipt_number', sa.String(length=40), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'receipt_number', name='uq_payment_org_receipt')
    )
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_org_id'), ['org_id'], unique=False)

    op.create_table('tasa_mantenimiento_ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('importe', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('descuento_tipo', sa.Enum('NONE', 'PENSIONISTA', name='ticket_descuento_tipo'), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'FACTURADO', 'COBRADO', name='ticket_estado'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contrato_id'], ['derecho_funerario_contrato.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'contrato_id', 'anio', name='uq_ticket_contract_year')
    )
    with op.batch_alter_table('tasa_mantenimiento_ticket', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasa_mantenimiento_ticket_org_id'), ['org_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasa_mantenimiento_ticket', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasa_mantenimiento_ticket_org_id'))

    op.drop_table('tasa_mantenimiento_ticket')
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_org_id'))
        batch_op.drop_index(batch_op.f('ix_payment_invoice_id'))

    op.drop_table('payment')
    with op.batch_alter_table('titularidad', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_titularidad_org_id'))

    op.drop_table('titularidad')
    with op.batch_alter_table('orden_trabajo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orden_trabajo_org_id'))

    op.drop_table('orden_trabajo')
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_org_id'))

    op.drop_table('invoice')
    with op.batch_alter_table('beneficiario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_beneficiario_org_id'))

    op.drop_table('beneficiario')
    with op.batch_alter_table('sepultura_ubicacion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sepultura_ubicacion_org_id'))

    op.drop_table('sepultura_ubicacion')
    with op.batch_alter_table('sepultura_difunto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sepultura_difunto_org_id'))

    op.drop_table('sepultura_difunto')
    with op.batch_alter_table('movimiento_sepultura', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movimiento_sepultura_sepultura_id'))
        batch_op.drop_index(batch_op.f('ix_movimiento_sepultura_org_id'))
        batch_op.drop_index(batch_op.f('ix_movimiento_sepultura_fecha'))

    op.drop_table('movimiento_sepultura')
    with op.batch_alter_table('inscripcion_lateral', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inscripcion_lateral_org_id'))

    op.drop_table('inscripcion_lateral')
    with op.batch_alter_table('expediente', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expediente_org_id'))

    op.drop_table('expediente')
    with op.batch_alter_table('derecho_funerario_contrato', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_derecho_funerario_contrato_org_id'))

    op.drop_table('derecho_funerario_contrato')
    with op.batch_alter_table('sepultura', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sepultura_org_id'))

    op.drop_table('sepultura')
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_person_org_id'))

    op.drop_table('person')
    op.drop_table('membership')
    with op.batch_alter_table('lapida_stock', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lapida_stock_org_id'))

    op.drop_table('lapida_stock')
    with op.batch_alter_table('cemetery', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cemetery_org_id'))

    op.drop_table('cemetery')
    op.drop_table('user_account')
    op.drop_table('organization')
    # ### end Alembic commands ###
